### ISSUE TITLE
"ModuleNotFoundError: Could not find module in path: 'gridjs-vue/dist/themes/mermaid.css'

### ISSUE THREAD

**Issue by afshinm** [grid-js/gridjs-vue#22]
I'm getting this error after installing the module:

```
 "ModuleNotFoundError: Could not find module in path: 'gridjs-vue/dist/themes/mermaid.css' relative to '/node_modules/gridjs-vue/dist/index.esm.js'"
```

which I believe is because of this symlink `https://github.com/grid-js/gridjs-vue/blob/master/dist/themes`

**Comment by afshinm** [comment]
In general, a wrapper should NOT export the main library files and this line https://github.com/grid-js/gridjs-vue/blob/master/package.json#L32 should be removed and replaced with `peerDependency`.

**Comment by afshinm** [comment]
This is my Codesandbox: https://codesandbox.io/s/nervous-franklin-e028t?file=/src/components/HelloWorld.vue -- lmk if I'm doing something wrong.

**Comment by lysla** [comment]
Hi, I was about to try gridjs vue wrapper and I'm getting the same problem. 
I also believe it is because of the symlink. But i think the symlink its actually pointing to itself? Where should it point to instead?

```
ERROR  Failed to compile with 1 errors
This relative module was not found:
* ./themes in ./node_modules/gridjs-vue/dist/index.esm.js
```

I also get this warning from the linter on the import line:
`Could not find a declaration file for module 'gridjs-vue'.`
But that doesn't seem to stop the import itself, so its a minor issue.

**Comment by lysla** [comment]
While we wait for a more stable solution, i fixed it changing the source file in node_modules/gridjs-vue/src/gridjs-vue.vue at line 147 like this:
```await import(`gridjs/dist/theme/${this.theme}.css`);```

**Comment by lysla** [comment]
> While we wait for a more stable solution, i fixed it changing the source file in node_modules/gridjs-vue/src/gridjs-vue.vue at line 147 like this:
> `` await import(`gridjs/dist/theme/${this.theme}.css`); ``
> 
> Note: since this means the main import in Vue needs to take the source file and not the dist one, it needs to be specified as follow:
> 
> ```
> import Grid from 'gridjs-vue/src/index';
> Vue.use(Grid);
> ```

Update: that actually fixes the error on compiling but the component does not work. It give a CSS related error:
`DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules`

**Comment by afshinm** [comment]
thanks @lysla 

I believe @selfagency is currently looking into this issue and I'm hoping to have a new version soon.

**Comment by selfagency** [comment]
Try version 0.3.2 now on npm.

**Comment by selfagency** [comment]
@afshinm I have 0.3.2 working locally but when I try it on CodeSandbox, I run into a weird bug. I mentioned it to the founder here: https://twitter.com/self_agency/status/1277064527583027202?s=20

Per the dependency thing, I suppose I could or even should decouple Grid.js and have it as a peer dependency, but then people would have to remember to install both `gridjs` and `gridjs-vue`, and keep the versions in sync in case there are any disparities caused by breaking changes in the API.

**Comment by afshinm** [comment]
@selfagency did you see this reply: https://twitter.com/CompuIves/status/1277178550773256193?

I'm not entirely sure if it's a Grid.js bug?

**Comment by selfagency** [comment]
Working now thanks to his help! https://codesandbox.io/s/gridjs-vue-hm25m?file=/src/App.vue

**Comment by afshinm** [comment]
Great! I can confirm that it's fixed.

**Comment by selfagency** [comment]
What do you want to do about the dep vs peer dep situation?

**Comment by afshinm** [comment]
@selfagency I think the current implementation is ok. I've explored other wrappers and seen some where they added the main lib as dev or peer dependency.
